#!/bin/bash
set -eu
[ -n "$DEBUG" ] && set -x

if [ -z "${PLAYLIST_LINK:-}" ]
then
	echo "Set \$PLAYLIST_LINK to the link to the YouTube playlist."
	exit 1
fi

FORMAT=${FORMAT:-bestvideo+bestaudio}
OUTPUT_TEMPLATE=${OUTPUT_TEMPLATE:-%(playlist_index)s - %(uploader)s - %(title)s.%(ext)s}
SLEEP_TIME=${SLEEP_TIME:-24h}

while true
do
	/usr/local/bin/yt-dlp -f $FORMAT --concurrent-fragments 8 --ignore-errors --compat-options playlist-index --cookies /etc/cookies.txt --download-archive /etc/archive.txt --yes-playlist --no-overwrites --embed-subs --write-sub --add-metadata --write-info-json --write-description --write-annotation --write-thumbnail --playlist-reverse --output "/downloads/$OUTPUT_TEMPLATE" ${EXTRA_OPTIONS:-} "$PLAYLIST_LINK"
	sleep "$SLEEP_TIME"
done

